name: Scheduled Maintenance

on:
  schedule:
    # Runs at 2 AM UTC every day
    - cron: '0 2 * * *'

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run maintenance script
        run: python maintenance_task.py

      - name: Notify completion
        run: echo "Maintenance task completed successfully."

